ersion: 2
jobs:
  build:
    docker:
      - image: jetcipher/circleci-dotnet-core:3.0
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: ShechterShoppingList
      - run:
          name: Build
          command: |
              mkdir /tmp/artifacts;
              dotnet build -c Release --runtime linux-x64 -o /tmp/artifacts
          working_directory: ShechterShoppingList
          
      - store_artifacts:
          path: /tmp/artifacts
#      - setup_remote_docker:
#          docker_layer_caching: false
#      - run:
#          name: Build and push Docker image
#          command: |
#            docker build -t shechtershoppinglist .
#            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
#            docker tag circleci itay47/shechtershoppinglist
#            docker push itay47/shechtershoppinglist
