version: 2
jobs:
  build:
    docker:
      - image: itay47/circleci-dotnet-core:3.1
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: ShechterShoppingList
      - run:
          name: Build
          command: |
              mkdir /tmp/artifacts;
              dotnet build -c Release --runtime linux-x64 -o /tmp/artifacts
          working_directory: ShechterShoppingList
          
      - store_artifacts:
          path: /tmp/artifacts
                    
      # build image
      - run:
          name: Build_Image  
          command: |
              docker info
              docker build -t shechtershoppinglist:heroku -f Dockerfile .
              
  manual_release_to_heroku:
    steps:
      # deploy the image
      - run: 
          name: Deploy_to_Heroku
          command: |
              docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
              docker tag shechtershoppinglist:heroku registry.heroku.com/shechtershoppinglist/web
#              docker push registry.heroku.com/shechtershoppinglist/web                
              curl https://cli-assets.heroku.com/install.sh | sh
              heroku container:push web -a shechtershoppinglist
              heroku container:release web -a shechtershoppinglist
              
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - manual_release_to_heroku:
          type: approval
          requires:
            - build
         
#      - setup_remote_docker:
#          docker_layer_caching: false
#      - run:
#          name: Build and push Docker image
#          command: |
#            docker build -t shechtershoppinglist .
#            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
#            docker tag circleci itay47/shechtershoppinglist
#            docker push itay47/shechtershoppinglist
